"""Tests for TIN comparison parsing and reporting."""

from pathlib import Path
import struct
import sys


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from src.compare_tin_files import compare_tin_files, parse_tin_file, render_comparison_report


def test_compare_tin_files_reports_exact_match_for_identical_text_exports(tmp_path):
    manual_path = tmp_path / "manual.tin"
    generated_path = tmp_path / "generated.tin"
    content = """# TIN File: Sample Surface
# Generated by TinForge
# Points: 3
# Triangles: 1

POINTS
1 0.0000 0.0000 100.0000
2 10.0000 0.0000 100.0000
3 0.0000 10.0000 101.0000

TRIANGLES
1 1 2 3
"""

    manual_path.write_text(content, encoding="utf-8")
    generated_path.write_text(content, encoding="utf-8")

    comparison = compare_tin_files(manual_path, generated_path)
    report = render_comparison_report(comparison)

    assert comparison.equivalent is True
    assert "VALIDATION RESULT: ✓ FILES MATCH" in report


def test_parse_binary_tp3_probe_extracts_project_name_and_points(tmp_path):
    tp3_path = tmp_path / "manual.tp3"
    header = (
        b"Topcon TP3"
        + b"\x00" * 18
        + "Synthetic Surface".encode("utf-16le")
        + b"\x00" * 24
    )
    points = [
        (100.0, 100.0, 150.0),
        (120.0, 100.0, 150.5),
        (105.0, 115.0, 151.0),
        (118.0, 130.0, 152.0),
    ]
    records = [struct.pack("<ddd", *point) for point in points]
    tp3_path.write_bytes(header + b"".join(records))

    parsed = parse_tin_file(tp3_path)

    assert parsed.source_format == "topcon_binary_tp3"
    assert parsed.name == "Synthetic Surface"
    assert len(parsed.points) == 4
    assert parsed.metadata["triangle_source"] == "inferred_delaunay"
    assert len(parsed.triangles) == 2
    assert {triangle_point for triangle in parsed.triangles for triangle_point in triangle} == {1, 2, 3, 4}


def test_compare_tin_files_respects_non_default_tolerances(tmp_path):
    manual_path = tmp_path / "manual.tin"
    generated_path = tmp_path / "generated.tin"
    manual_path.write_text(
        """# TIN File: Manual Surface
# Generated by TinForge
# Points: 3
# Triangles: 1

POINTS
1 100.0000 100.0000 100.0000
2 110.0000 100.0000 100.0000
3 100.0000 110.0000 100.0000

TRIANGLES
1 1 2 3
""",
        encoding="utf-8",
    )
    generated_path.write_text(
        """# TIN File: Generated Surface
# Generated by TinForge
# Points: 3
# Triangles: 1

POINTS
1 100.4000 100.4000 100.0000
2 110.4000 100.4000 100.0000
3 100.4000 110.4000 100.0000

TRIANGLES
1 1 2 3
""",
        encoding="utf-8",
    )

    comparison = compare_tin_files(
        manual_path,
        generated_path,
        coordinate_tolerance=1.0,
        bounds_tolerance_percent=10.0,
        area_tolerance_percent=10.0,
    )
    report = render_comparison_report(comparison)

    assert comparison.equivalent is True
    assert comparison.differences == []
    assert "bounds=10.00%" in report
    assert "area=10.00%" in report


def test_compare_tin_files_treats_two_empty_inputs_as_matching(tmp_path):
    manual_path = tmp_path / "manual_empty.tin"
    generated_path = tmp_path / "generated_empty.tin"
    content = """# TIN File: Empty Surface
# Generated by TinForge
# Points: 0
# Triangles: 0

POINTS

TRIANGLES
"""

    manual_path.write_text(content, encoding="utf-8")
    generated_path.write_text(content, encoding="utf-8")

    comparison = compare_tin_files(manual_path, generated_path)

    assert comparison.bounds_difference_percent == 0.0
    assert comparison.equivalent is True
