"""Export TIN data to Licai format (.tin, .dat)."""

from ..core.tin_model import TINModel


class LicaiExporter:
    """Export TIN model to Licai surveying system formats."""
    
    def export_tin(self, tin_model: TINModel, filepath: str) -> None:
        """
        Export to Licai .tin format.
        
        Format:
        #POINTS
        ID X Y Z [Description]
        #TRIANGLES
        ID Point1 Point2 Point3
        
        Args:
            tin_model: TIN model to export
            filepath: Output file path
        """
        with open(filepath, 'w', encoding='utf-8') as f:
            # Header
            f.write(f"# Licai TIN File: {tin_model.name}\n")
            f.write(f"# Generated by TinForge\n")
            f.write(f"# Points: {len(tin_model.points)}\n")
            f.write(f"# Triangles: {len(tin_model.triangles)}\n")
            f.write("\n")
            
            # Points section
            f.write("#POINTS\n")
            for point in tin_model.points:
                f.write(f"{point.id} {point.x:.4f} {point.y:.4f} {point.z:.4f}")
                if point.description:
                    f.write(f" {point.description}")
                f.write("\n")
            f.write("\n")
            
            # Triangles section
            f.write("#TRIANGLES\n")
            for triangle in tin_model.triangles:
                f.write(f"{triangle.id} {triangle.point1.id} {triangle.point2.id} {triangle.point3.id}\n")
    
    def export_dat(self, tin_model: TINModel, filepath: str) -> None:
        """
        Export to Licai .dat format (alternative format).
        
        Args:
            tin_model: TIN model to export
            filepath: Output file path
        """
        with open(filepath, 'w', encoding='utf-8') as f:
            # Licai .dat is typically a simpler coordinate listing
            f.write(f"LICAI_DAT_FORMAT\n")
            f.write(f"Name: {tin_model.name}\n")
            f.write(f"PointCount: {len(tin_model.points)}\n")
            f.write(f"TriangleCount: {len(tin_model.triangles)}\n")
            f.write("\n")
            
            # Points with tab separation (common in Licai)
            for point in tin_model.points:
                f.write(f"{point.id}\t{point.x:.4f}\t{point.y:.4f}\t{point.z:.4f}\n")
    
    def export_xyz(self, tin_model: TINModel, filepath: str) -> None:
        """
        Export to simple XYZ format (compatible with Licai).
        
        Args:
            tin_model: TIN model to export
            filepath: Output file path
        """
        with open(filepath, 'w') as f:
            for point in tin_model.points:
                f.write(f"{point.x:.4f} {point.y:.4f} {point.z:.4f}\n")
