"""Export TIN data to Topcon format (.tp3, .tin)."""

from typing import Optional
from ..core.tin_model import TINModel


class TopconExporter:
    """Export TIN model to Topcon machine control formats."""
    
    def export_tp3(self, tin_model: TINModel, filepath: str) -> None:
        """
        Export to Topcon .tp3 format (binary).
        
        Args:
            tin_model: TIN model to export
            filepath: Output file path
        """
        # .tp3 is Topcon's native binary format
        # This is a simplified text representation for reference
        with open(filepath, 'w') as f:
            f.write(f"TOPCON_TP3_FORMAT\n")
            f.write(f"Name: {tin_model.name}\n")
            f.write(f"Points: {len(tin_model.points)}\n")
            f.write(f"Triangles: {len(tin_model.triangles)}\n")
            f.write("\n")
            
            # Points section
            f.write("[POINTS]\n")
            for point in tin_model.points:
                f.write(f"{point.id}\t{point.x:.4f}\t{point.y:.4f}\t{point.z:.4f}\n")
            f.write("\n")
            
            # Triangles section
            f.write("[TRIANGLES]\n")
            for triangle in tin_model.triangles:
                f.write(f"{triangle.id}\t{triangle.point1.id}\t{triangle.point2.id}\t{triangle.point3.id}\n")
            
            # Breaklines section
            if tin_model.breaklines:
                f.write("\n[BREAKLINES]\n")
                for bl_idx, breakline in enumerate(tin_model.breaklines):
                    f.write(f"Breakline_{bl_idx}: ")
                    f.write(" ".join(str(p.id) for p in breakline))
                    f.write("\n")
            
            # Boundary section
            if tin_model.boundary:
                f.write("\n[BOUNDARY]\n")
                for boundary_point in tin_model.boundary:
                    f.write(f"{boundary_point.id}\t{boundary_point.x:.4f}\t{boundary_point.y:.4f}\n")
    
    def export_tin(self, tin_model: TINModel, filepath: str) -> None:
        """
        Export to generic .tin format.
        
        Args:
            tin_model: TIN model to export
            filepath: Output file path
        """
        # Generic TIN text format
        with open(filepath, 'w') as f:
            # Header
            f.write(f"# TIN File: {tin_model.name}\n")
            f.write(f"# Generated by TinForge\n")
            f.write(f"# Points: {len(tin_model.points)}\n")
            f.write(f"# Triangles: {len(tin_model.triangles)}\n")
            f.write("\n")
            
            # Points
            f.write("POINTS\n")
            for point in tin_model.points:
                f.write(f"{point.id} {point.x:.4f} {point.y:.4f} {point.z:.4f}")
                if point.description:
                    f.write(f" # {point.description}")
                f.write("\n")
            f.write("\n")
            
            # Triangles
            f.write("TRIANGLES\n")
            for triangle in tin_model.triangles:
                f.write(f"{triangle.id} {triangle.point1.id} {triangle.point2.id} {triangle.point3.id}\n")
    
    def export_xml_landxml(self, tin_model: TINModel, filepath: str) -> None:
        """
        Export to LandXML format for interoperability.
        
        Args:
            tin_model: TIN model to export
            filepath: Output file path
        """
        # Simplified LandXML structure
        xml_lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<LandXML xmlns="http://www.landxml.org/schema/LandXML-1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">',
            f'  <Project name="{tin_model.name}">',
            '    <Surface name="TinSurface">',
            '      <DefinitionType>TIN</DefinitionType>',
            '      <Points>',
        ]
        
        # Add points
        for point in tin_model.points:
            xml_lines.append(
                f'        <Point id="{point.id}"><Coordinates><X>{point.x:.4f}</X><Y>{point.y:.4f}</Y><Z>{point.z:.4f}</Z></Coordinates></Point>'
            )
        
        # Add triangles
        xml_lines.extend([
            '      </Points>',
            '      <Faces>',
        ])
        
        for triangle in tin_model.triangles:
            xml_lines.append(
                f'        <Face id="{triangle.id}"><Pt>{triangle.point1.id}</Pt><Pt>{triangle.point2.id}</Pt><Pt>{triangle.point3.id}</Pt></Face>'
            )
        
        xml_lines.extend([
            '      </Faces>',
            '    </Surface>',
            '  </Project>',
            '</LandXML>',
        ])
        
        with open(filepath, 'w') as f:
            f.write('\n'.join(xml_lines))
